sudo: required
os: linux
arch:
  - arm64
language: node_js
node_js:
  - "14"
  
addons:
  chrome: stable
 
before_script:
  - npm install -g protractor
  - npm install -g webdriver-manager
  - webdriver-manager update
  - webdriver-manager start &
  - sleep 5

script:
  - protractor conf.js