sudo: required
os: linux
arch:
  - arm64
  - ppc64le
  - s390x
language: node_js
node_js:
  - "14"
  
addons:
  chrome: stable
 
before_script:
  - npm install -g protractor
  - webdriver-manager update
  - webdriver-manager start &
  - sleep 5

script:
  - protractor conf.js
